{% set name = "sphinxcontrib-bibtex" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 887647a1390857278b005f0ecd4eab8df967bfb34cb52a8fcf1150b5020cbcb9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - pybtex >=0.20
    - pybtex-docutils >=0.2.0
    - six >=1.4.1
    - sphinx >=2.0
    - oset >=0.1.3
  run:
    - python >=3.5
    - pybtex >=0.20
    - pybtex-docutils >=0.2.0
    - six >=1.4.1
    - sphinx >=2.0
    - oset >=0.1.3

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.bibtex

about:
  home: https://github.com/mcmtroffaes/sphinxcontrib-bibtex
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A Sphinx extension for BibTeX style citations.
  description: This extension allows BibTeX citations to be inserted into documentation generated by Sphinx."
  doc_url: http://sphinxcontrib-bibtex.readthedocs.org/en/latest/
  dev_url: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/

extra:
  recipe-maintainers:
    - croth1
