travis:
  secure:
    BINSTAR_TOKEN: ADqedmsqXyzxgD3/zM7Clqzv/RFzBYdmZvjxokgyEGK9Q8zo/h7GeTSEmiipVW5TtmMPu6xVV/Y/rvotI9A6M7COTNRpzn5U/KmG7XL13ksbsfr+fwNfxJpIuPaflMdNvfGXP2r2UXXOg1Si0M1aCHIHl99azhx6AycFBrEljOtaeFerg36WCFhA46vFDCkt81LMcmxITn1eYcNaoVtlZQ9tpmdmyu4A7zFcN1rrZr1c9mzEXBimAQAOttyUd/6c3FRMeNrMQu/abtu/n0ilD183d+Aq0AQ1oszBZk2obo5G1TtsPEp2fppWLoVWzTtGPlpVhDsPw9ZkxFSg4DTAmfmnFD3ujzHVc3PW0uOndZVwFtGlrCRyQpczxxPyno9Ctwl5g9b+ZsEXCeCl/FkMzKS95IOfiDVaCkpxEzUxWTVULFy41eFqS1durCjLEUXy0G1eGpFHTJtOIFrMd9VU69lkrvdRUOSXBjpbKaxzmW9BrqBUKuh57HRXSQlh5SORwyP/OBdxE3oy3Y6pjtQqt5dklCubwT81JTtwdfhFp19Pk9Ci85JFZLS733Jvgr4xm1j2ziKMDfWtkZuoEmLXqU3VyanG6S4V/VtX+vY7d7+IQ7TsbxNajdxp96XCnOdVCzEbZHyzKEPHk2gwsRux7v+R85VjFXKkbw9mUVzsv+w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
